# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jaeho's Blog
email: reachme@jaeho.me
description: >- # this means to ignore newlines until "baseurl:"
  This my blog to write about my hobbies and interests!
baseurl: "" # the subpath of your site
url: "https://blog.jaeho.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: N/A
github_username: koda-git

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

enable_copy_code_button: true
search: true

# Defaults
defaults:
  # posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      categories: ""
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

author:
  name: "Jaeho"
  avatar: "https://avatars.githubusercontent.com/u/85606515?v=4"
  bio: "I am a Level 3 Computer Science student at Mac. I enjoy programming, gaming, and learning new things!"
  location: "Toronto, Ontario"
  links:
    - label: "Email"
      # icon: "fas fa-fw fa-envelope-square"
      url: "mailto:reachme@jaeho.me"
    - label: "Website"
      # icon: "fas fa-fw fa-link"
      url: "https://jaeho.me"
    - label: "GitHub"
      # icon: "fab fa-fw fa-github"
      url: "https://github.com/koda-git"

locale: "en-US"
