services:
  jekyll:
    image: ruby:3.3-slim
    container_name: jekyll-site
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=production
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: sh -c "apt-get update && apt-get install -y build-essential && gem install bundler && bundle install && jekyll serve --host 0.0.0.0"
