services:
  jekyll:
    image: ruby:3.3.0-alpine
    container_name: jekyll-site
    working_dir: /srv/jekyll
    environment:
      - JEKYLL_ENV=production
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: sh -c "apk add --no-cache build-base && gem install bundler && bundle install && jekyll serve --host 0.0.0.0"
